services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 3306:3306
      - 5432:5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
      - ./log:/var/log
      - $CERTIFICATI_HTTPS:/certs/

  whoami:
    image: traefik/whoami
    container_name: whoami-service
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`gabri.docker.appdev`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.domains[0].main=gabri.docker.appdev"

  postgres:
    image: postgres:16.3-bookworm
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_pg_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres_db.rule=HostSNI(`pg1.docker.appdev`)"
      - "traefik.tcp.routers.postgres_db.entrypoints=postgres"
      - "traefik.tcp.routers.postgres_db.tls=true"
      - "traefik.tcp.routers.postgres_db.tls.domains[0].main=pg1.docker.appdev"

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: pg_admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pg_admin.rule=Host(`pgadmin.docker.appdev`)"
      - "traefik.http.routers.pg_admin.entrypoints=websecure"
      - "traefik.http.routers.pg_admin.tls=true"
      - "traefik.http.routers.pg_admin.tls.domains[0].main=pgadmin.docker.appdev"

volumes:
  db_pg_data:
   driver: local
  pgadmin_data:
   driver: local

networks:
  default:
   name: win-dev-docker-recipe_default