services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 3306:3306
      - 5432:5432
    networks:
      - default
      - external_bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
      - ./log:/var/log
      - $CERTIFICATI_HTTPS:/certs/

  whoami:
    image: traefik/whoami
    container_name: whoami-service
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`gabri.docker.appdev`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.domains[0].main=gabri.docker.appdev"

  mysql:
    image: mysql:8.4
    container_name: mysql_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - db_mysql_data:/var/lib/mysql  
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql_db.rule=HostSNI(`mysql1.docker.appdev`)"
      - "traefik.tcp.routers.mysql_db.entrypoints=mysql"
      - "traefik.tcp.routers.mysql_db.tls=true"
      - "traefik.tcp.routers.mysql_db.tls.domains[0].main=mysql1.docker.appdev"     

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`pma.docker.appdev`)"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls=true"
      - "traefik.http.routers.pma.tls.domains[0].main=pma.docker.appdev"

  postgres:
    image: postgres:16.3-bookworm
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_pg_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres_db.rule=HostSNI(`pg1.docker.appdev`)"
      - "traefik.tcp.routers.postgres_db.entrypoints=postgres"
      - "traefik.tcp.routers.postgres_db.tls=true"
      - "traefik.tcp.routers.postgres_db.tls.domains[0].main=pg1.docker.appdev"

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: pg_admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pg_admin.rule=Host(`pgadmin.docker.appdev`)"
      - "traefik.http.routers.pg_admin.entrypoints=websecure"
      - "traefik.http.routers.pg_admin.tls=true"
      - "traefik.http.routers.pg_admin.tls.domains[0].main=pgadmin.docker.appdev"

volumes:
  db_mysql_data:
    driver: local
  db_pg_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: win-dev-docker-recipe_default
  external_bridge:
    name: external_bridge_traefik
