http:
  routers:
    api:
      rule: Host(`reverse-proxy.docker.appdev`)
      service: api@internal
      tls: true
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/_wildcard.docker.appdev.pem
        keyFile: /certs/_wildcard.docker.appdev-key.pem
  certificates:
    - certFile: /certs/reverse-proxy.docker.appdev.pem
      keyFile: /certs/reverse-proxy.docker.appdev-key.pem
    - certFile: /certs/_wildcard.docker.appdev.pem
      keyFile: /certs/_wildcard.docker.appdev-key.pem
