log:
  level: DEBUG
  filePath: "/var/log/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"

api:
  insecure: false
  dashboard: true

providers:
  file:
    directory: "/etc/traefik"
    watch: true
  docker:
    watch: true
    exposedByDefault: false

ping: { }

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
  mysql:
    address: :3306
  

